### PR TITLE
[WIP] Clean up the readme a bit and add a .gitignore to avoid assets being committed into the repo

### PR DESCRIPTION
**Pull request by CrashOveride95**
This PR when done will aim to make the readme easier to read and proofread.

### CODE REVIEW

**Comment by Erick194** [comment]
Great, it looks neater now. Thanks for the input. 🙂

**Comment by CrashOveride95** [comment]
aw but i wasn't finished yet :(

**Comment by Erick194** [comment]
Oops, excuse me, do another pull, no problem .😅

**Comment by Erick194** [comment]
Only put it on as part 2

**Pull request merged**
